version: 2
update-subdependencies: true
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: increase
    pull-request-branch-name:
      separator: "-"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 10
    groups:
      vitest:
        dependency-type: "direct"
        update-type: "all"
      js-yaml:
        dependency-type: "direct"
        update-type: "all"
      postcss:
        dependency-type: "direct"
        update-type: "all"
